### ISSUE TITLE
Feature request: create dictionary descriptive analyzer that lacks +Err/Frag analyses

### ISSUE THREAD

**Issue by eddieantonio** [giellalt/lang-crk#17]
Produce a descriptive analyzer that eliminates `+Err/Frag` analyses, as well as removes the `+Err/Orth` tag.
This FST could be created in `quick.mk`; not necessarily required in the primary build system.

This will elimate downstream applications (namely, _itwêwina_) from having to manually filter out `+Err/Frag` analyses.

@aarppe: any comments?

**Comment by aarppe** [comment]
This would be the regexp code:

`regex ~[ $[ "+Err/Frag" ] ] .o. [ "+Err/Orth" -> 0 ] ;`

Since these are needed in particular for _itwêwina_, they can be done outside that standard FST scheme, i.e. only in `quick.mk`.

Also, as they are dictionary specific FSTs, one could resurrect the code `dict`, e.g. as `crk-analyzer-relaxed-dict.hfst`
