### ISSUE TITLE
Use correct configure flags automatically OR clearly document correct usage

### ISSUE THREAD

**Issue by eddieantonio** [giellalt/lang-crk#3]
> > ./configure --without-xfst --with-hfst --with-foma
> 
> Perfect, this worked.

> Where is that documented? El mié., 24 de jun. de 2020 13:57, aarppe <notifications@github.com> escribió:
> […](#)

@aarppe Is there anyway we can have this in the output of the autogen.sh that tells you to do an ./configure ?

_Originally posted by @atticusha in https://github.com/giellalt/lang-crk/issues/2#issuecomment-649048199_

**Comment by aarppe** [comment]
This would vary from language to language. Sjur was intending to make the above configuration default, but then there are folks who are too used to using XFST.

Options for `./configure` can be found as follows:

`./configure -h`

Sjur is aware that they should document more, in particular taking into account how things have changed with the migration to Github.

**Comment by eddieantonio** [comment]
But now that everything is in separate repositories, can we not simply have the correct options exist in this repository only? @snomos, would this cause any issues?

**Comment by snomos** [comment]
Separate repositories does not really change anything. And yes, there would be issues related to scalability: it greatly increases the risk of merge conflicts when doing changes across all repositories to the config files. The ability to host, maintain and develop many languages depends on a clear separation of what is language specific and what is language independent, so that all the independent parts can be updated using a simple diff merge based on changes in a template repository.

That does not mean we can't accomodate to these needs. The autoconf files are split in two: the main `configure.ac`, and the files in the `m4/` directory. These files have developed so that `configure.ac` contains mainly language specific information, the rest is language-independent settings, which includes the defaults for fst compilation engines.

My idea is to add language specific overrides to `configure.ac`, but this has to be done consistently for all languages before the actual values can be tuned to the needs of each language. It is also important to retain the possibility for each user to override any defaults at configure time.

Perhaps this is something that @flammie could look into during the summer?

**Comment by eddieantonio** [comment]
> Separate repositories does not really change anything. And yes, there would be issues related to scalability: it greatly increases the risk of merge conflicts when doing changes across all repositories to the config files. The ability to host, maintain and develop many languages depends on a clear separation of what is language specific and what is language independent, so that all the independent parts can be updated using a simple diff merge based on changes in a template repository.

Hi Sjur. This seems really strange to me. I've worked on plenty of software projects before, and I have never encountered any project that requires wholesale changes to a number of known repositories. Why is this ability copy-pasted across each repository? Would it not make more sense from a software development perspective if each repository is independent, but plugs into a _framework_, that is configurable, but independently updatable?

**Comment by bbqsrc** [comment]
Hey @eddieantonio, we've discussed it several times now, and at this stage, it was considered architecturally infeasible to shift to another working model at this time. There's so many moving parts in these repositories, and while this model is strange from a software development perspective, it seems to be working quite well from a linguist's perspective.

We just got them to move to git from svn, all things in good time, baby steps, etc. 😆

That said, it's an open discussion as far as I'm concerned, feel free to email me or ping me on Zulip if you want to have a chat about it.

**Comment by aarppe** [comment]
Hey all - this is a discussion we'd need to have - and perhaps not as a Github issue. As far as concerns me, one would want to identify what is minimally required for various aspects of the GT infrastructure to provide the goodies it can (e.g. spell-checkers), while allowing for local variations. But the details of this are a longer issue.

**Comment by snomos** [comment]
First of all, this ~~bug~~ feature request is not specific to crk, and I have created a new issue that is linked to above, repeated here: giellalt/template-lang-und#2. Please continue the technical discussions there.

For the more overall discussions regarding the development of the infrastructure, I suggest we do that in a suitable [Zulip thread](https://giella.zulipchat.com/#narrow/stream/245319-giellalt-infra/topic/Generalisable.20build.20code).
