### ISSUE TITLE
`minihkwahastimwêw' is not in the model 

### ISSUE THREAD

**Issue by atticusha** [giellalt/lang-crk#39]
`minihkwahastimwêw` is not in the model, but is in the AW corpus. It is the case that `minihkwahatimwêw` returns on itwêwina, though this does not seem to have access to the inflectional paradigms morphology. Further, it doesn't seem to exist in my 

`minihkwahatimwêw` does not appear to be analyzed by `src/crk-relaxed-analyzer-giellaltbuild.hfstol`. Despite this, the stem appears to exist in the verb stems file. Weirdly, it is coded as a VTA, despite returning as a VAI in itwêwina.

**Comment by fbanados** [comment]
We had some delay in integrating changes from updates to the altlab dictionary sources.  Currently, `minihkwahastimwêw` has replaced the entry for `minihkwahatimwêw` in the verb stems file, so this issue is solved for this repository.  These changes have not been pushed to the main itwêwina, but are already available in the development branch deployment, with inflectional paradigms morphology. (https://itwewina.altlab.dev/word/minihkwahastimwêw/)

We expect to deploy a new version to the main server soon.
