### ISSUE TITLE
What is pahkat and why does it hate me?

### ISSUE THREAD

**Issue by eddieantonio** [giellalt/lang-crk#4]
The Speller bundler keeps failing here:

https://github.com/giellalt/lang-crk/runs/851821671#step:8:107

This is the workflow:

https://github.com/giellalt/lang-crk/blob/develop/.github/workflows/spellers-selfhosted.yml

What is pahkat? Who is causing these failures? Can I safely ignore this? 

@bbqsrc, I'm @'ing you because you committed the workflow script 😂

**Comment by aarppe** [comment]
What I know is that pahkat is the repository that Divvun is using for making available the Divvun keyboards (and spell-checkers). Dunno properly about the rest.

**Comment by bbqsrc** [comment]
@eddieantonio yes, it's fine. That specific deployment issue is because the version in the repository is not in semantic version format (ie, it's not x.y.z, it's only x.y). Fixing that, however, will still result in a deployment failure because I changed the deployment server and ran out of time to change all the languages before I went on vacation (I am on vacation now 😉)

Pahkat is our package management tool for delivering spellers, keyboards and other tools to Windows, macOS, Linux, iOS and Android. Divvun Installer on macOS and Windows are the user interfaces for this. The newest versions of these are yet to be released.

I return in early August, and I intend to begin documenting some induction documentation for our systems, with a mind to clarifying what everything is, and where it is, for all new stakeholders. 😄 We went from having basically two or three active participants to five or six, so apologies for the teething issues but we'll get there.

Keep asking questions though, it makes it clear what I need to document!
